CREATE TABLE estado (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NOT NULL,
	CONSTRAINT estado_pkey PRIMARY KEY (id)
);

CREATE TABLE cidade (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NOT NULL,
	estado_id int8 NOT NULL,
	CONSTRAINT cidade_pkey PRIMARY KEY (id),
	CONSTRAINT fkkworrwk40xj58kevvh3evi500 FOREIGN KEY (estado_id) REFERENCES estado(id)
);

CREATE TABLE cozinha (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NOT NULL,
	CONSTRAINT cozinha_pkey PRIMARY KEY (id)
);

CREATE TABLE forma_pagamento (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255) NULL,
	CONSTRAINT forma_pagamento_pkey PRIMARY KEY (id)
);

CREATE TABLE permissao (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255) NULL,
	nome varchar(255) NULL,
	CONSTRAINT permissao_pkey PRIMARY KEY (id)
);

CREATE TABLE restaurante (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	data_atualizacao timestamp NOT NULL,
	data_cadastro timestamp NOT NULL,
	endereco_bairro varchar(255) NULL,
	endereco_cep varchar(255) NULL,
	endereco_complemento varchar(255) NULL,
	endereco_logradouro varchar(255) NULL,
	endereco_numero varchar(255) NULL,
	nome varchar(255) NOT NULL,
	taxa_frete numeric(19, 2) NULL,
	cozinha_id int8 NOT NULL,
	endereco_cidade_id int8 NULL,
	CONSTRAINT restaurante_pkey PRIMARY KEY (id),
	CONSTRAINT fk76grk4roudh659skcgbnanthi FOREIGN KEY (cozinha_id) REFERENCES cozinha(id),
	CONSTRAINT fkbc0tm7hnvc96d8e7e2ulb05yw FOREIGN KEY (endereco_cidade_id) REFERENCES cidade(id)
);

CREATE TABLE produto (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ativo bool NOT NULL,
	descricao varchar(255) NOT NULL,
	nome varchar(255) NOT NULL,
	preco numeric(19, 2) NOT NULL,
	resturante_id int8 NOT NULL,
	CONSTRAINT produto_pkey PRIMARY KEY (id),
	CONSTRAINT fko5kpn5npd5excw83fsvogx5pg FOREIGN KEY (resturante_id) REFERENCES restaurante(id)
);

CREATE TABLE restaurante_forma_pagamento (
	restaurante_id int8 NOT NULL,
	forma_pagamento_id int8 NOT NULL,
	CONSTRAINT fk7aln770m80358y4olr03hyhh2 FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento(id),
	CONSTRAINT fka30vowfejemkw7whjvr8pryvj FOREIGN KEY (restaurante_id) REFERENCES restaurante(id)
);


